#!/usr/bin/env node

/**
 * Token pipeline: design/tokens.json (DTCG, source of truth) → app/tokens.css (generated).
 *
 * Run after any approved change to design/tokens.json:
 *   node scripts/build-tokens.mjs
 *
 * What it emits:
 *   :root        — semantic colors (default-theme values — dark in this template), radius scale,
 *                  shadows, component tokens as CSS custom properties
 *   .light       — light-mode overrides, taken from each token's $extensions.modes.light
 *   @theme inline — maps the CSS variables to Tailwind v4 utility names
 *                  (bg-primary, text-muted-foreground, rounded-lg, shadow-xs, …)
 *
 * What it deliberately does NOT emit:
 *   primitive spacing / fontSize / lineHeight / breakpoints — these match Tailwind's
 *   defaults 1:1; emitting them would add noise without changing output.
 *   Font FILES — fonts load via next/font in app/layout.tsx with
 *   variable: "--font-sans" / "--font-mono"; this file only wires the utility names.
 *   The required family names live in design/tokens.json → primitive.fontFamily.
 */

import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(repoRoot, "design", "tokens.json");
const OUT = join(repoRoot, "app", "tokens.css");

const tokens = JSON.parse(readFileSync(SRC, "utf8"));

// ---- Resolve {group.path.name} references, with cycle detection ----

function lookup(path) {
  let node = tokens;
  for (const key of path.split(".")) {
    node = node?.[key];
    if (node === undefined) return undefined;
  }
  return node;
}

function resolve(value, seen = new Set()) {
  if (typeof value !== "string") return value;
  const m = value.match(/^\{([^}]+)\}$/);
  if (!m) return value;
  const path = m[1];
  if (seen.has(path)) {
    console.error(`ERROR: circular token reference at {${path}}`);
    process.exit(1);
  }
  seen.add(path);
  const target = lookup(path);
  if (target === undefined || target.$value === undefined) {
    console.error(`ERROR: unresolved token reference {${path}} — check design/tokens.json`);
    process.exit(1);
  }
  return resolve(target.$value, seen);
}

function shadowToCss(v) {
  return `${v.offsetX} ${v.offsetY} ${v.blur} ${v.spread} ${v.color}`;
}

// ---- Collect ----

const rootVars = [];   // ["--background: #000000", ...]
const lightVars = [];
const themeVars = [];  // Tailwind v4 @theme inline mappings

// Semantic colors → --<name> (dark) + .light override + --color-<name> theme mapping
for (const [name, def] of Object.entries(tokens.semantic?.color ?? {})) {
  rootVars.push(`--${name}: ${resolve(def.$value)};`);
  themeVars.push(`--color-${name}: var(--${name});`);
  const light = def.$extensions?.modes?.light;
  if (light !== undefined) lightVars.push(`--${name}: ${resolve(light)};`);
}

// Radius scale → --radius-<step>
for (const [step, def] of Object.entries(tokens.primitive?.borderRadius ?? {})) {
  rootVars.push(`--radius-${step}: ${resolve(def.$value)};`);
  themeVars.push(`--radius-${step}: var(--radius-${step});`);
}

// Compatibility alias: shadcn components derive sizes from a base --radius
if (tokens.primitive?.borderRadius?.lg) {
  rootVars.push(`--radius: ${resolve(tokens.primitive.borderRadius.lg.$value)};`);
}

// Shadows → --shadow-<name>
for (const [name, def] of Object.entries(tokens.semantic?.shadow ?? {})) {
  const v = resolve(def.$value);
  rootVars.push(`--shadow-${name}: ${typeof v === "object" ? shadowToCss(v) : v};`);
  themeVars.push(`--shadow-${name}: var(--shadow-${name});`);
}

// Component tokens → --<component>-<token> (not mapped into @theme; referenced directly)
for (const [comp, group] of Object.entries(tokens.component ?? {})) {
  for (const [name, def] of Object.entries(group)) {
    if (name.startsWith("$")) continue;
    rootVars.push(`--${comp}-${name}: ${resolve(def.$value)};`);
  }
}

// Font utilities → next/font defines --font-sans / --font-mono on <html>
const families = Object.keys(tokens.primitive?.fontFamily ?? {});
for (const fam of families) {
  themeVars.push(`--font-${fam}: var(--font-${fam});`);
}
const familyNote = families
  .map((f) => `${f}: ${resolve(tokens.primitive.fontFamily[f].$value)}`)
  .join(", ");

// ---- Emit ----

const css = `/*
 * GENERATED by scripts/build-tokens.mjs — DO NOT EDIT BY HAND.
 * Source of truth: design/tokens.json (protected file — changes need user approval).
 * Regenerate with: node scripts/build-tokens.mjs
 *
 * Both themes ship: :root holds the default theme's values (dark in this template); .light is the override class for the other theme.
 * Fonts: load via next/font in app/layout.tsx with variable "--font-<name>".
 * Required families (from tokens): ${familyNote}
 */

:root {
  ${rootVars.join("\n  ")}
}

.light {
  ${lightVars.join("\n  ")}
}

@theme inline {
  ${themeVars.join("\n  ")}
}
`;

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, css);
console.log(`tokens.css written: ${OUT}`);
console.log(`  ${rootVars.length} variables (:root), ${lightVars.length} light overrides, ${themeVars.length} Tailwind mappings`);
